# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean test

    - name: Extract failed tests
      run: |
        FAILED_TESTS=""
        for file in target/surefire-reports/*.xml; do
          if grep -q '<failure' "$file" || grep -q '<error' "$file"; then
            # Используем xmllint для получения имени теста и класса
            FAILED_TESTS+=$(xmllint --xpath "string(//testcase[failure or error]/@classname)" "$file")":"
            FAILED_TESTS+=$(xmllint --xpath "string(//testcase[failure or error]/@name)" "$file")" "
          fi
        done
        echo "FAILED_TESTS=${FAILED_TESTS}" >> $GITHUB_ENV

    - name: Send Telegram message on failure
      if: ${{ always() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          Тестирование завершилось со статусом ${{ job.status }}.
          ${{ job.status == 'failure' && format('Следующие тесты провалены: {0}', env.FAILED_TESTS) || 'Все тесты пройдены успешно.' }}
